/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;
import org.example.app.MessageUtils;


public class App {
    public static void main(String[] args) {

        MessageUtils exp =new MessageUtils();
        System.out.println(exp.getMessage());
    }
}
