/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;
import org.example.app.FlinkTest;

public class App {
    public static void main(String[] args)  throws Exception {

        FlinkTest testProcess =new FlinkTest();

        testProcess.testFlink();
    }



}
