/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;
import org.example.app.MessageUtils;
import org.apache.flink.api.common.functions.FlatMapFunction;
import org.apache.flink.api.java.tuple.Tuple2;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.util.Collector;


class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
